import { T, useTranslate } from "../../context/LanguageContext";
import { Link } from 'react-router-dom';
import { dashboardApi } from '../../api/api';
import { useWorkspace } from '../../context/WorkspaceContext';
import useResource from '../../hooks/useResource';
import { useMoney } from '../../components/Common';
import { ResourceState, Role, Totals } from '../../components/Template';
export default function Dashboard() {
  const money = useMoney();
  const tr = useTranslate();
  const r = useResource(dashboardApi.get),
    d = r.data,
    {
      yearId,
      year
    } = useWorkspace();
  return <ResourceState {...r}>{d && <div className="container py-4 dashboard-page"><div className="dashboard-heading"><div><p className="eyebrow"><T>{"THE BIG PICTURE"}</T></p><h1><T>{"Good work starts here."}</T></h1><p className="text-secondary"><T>{"Your people, projects, and purpose. All in one place."}</T></p></div></div><section className="impact-banner" aria-labelledby="impactTitle"><div><span className="eyebrow"><T>{"EVERY CONTRIBUTION COUNTS"}</T></span><h2 id="impactTitle"><T>{"A clearer view."}</T><br /><T>{"A greater impact."}</T></h2><p><T>{"Keep your community moving forward."}</T><br /><T>{"Explore your records and make the next thing happen."}</T></p><Role roles={['HEAD', 'SUBHEAD', 'MEMBER']}><Link to="/years" className="banner-link"><T>{"Explore yearly records"}</T> <i className="bi bi-arrow-up-right" /></Link></Role></div><div className="impact-art" aria-hidden="true"><div className="art-orbit orbit-one" /><div className="art-orbit orbit-two" /><div className="art-center"><i className="bi bi-flower2" /></div><span className="art-tag"><T>{"Growing together"}</T></span></div></section><div className="section-heading"><h2><T>{"Organization at a glance"}</T></h2><span><T>{"Across all years"}</T></span></div><section className="metric-grid" aria-label={tr("Organization totals")}>{[['mint', 'bi-people', 'Members', d.totalMembers, 'People in your community'], ['lavender', 'bi-kanban', 'Projects', d.totalProjects, 'Ideas put into action'], ['peach', 'bi-heart', 'Donations', d.totalDonationsCount, 'Contributions recorded'], ['sand', 'bi-calendar3', 'Yearly records', d.totalYears, 'Your impact over time']].map(([color, icon, label, value, caption]) => <div className="metric-card" key={label}><span className={`metric-icon ${color}`}><i className={`bi ${icon}`} /></span><span className="stat-label"><T>{label}</T></span><strong className="stat-value">{value}</strong><span className="metric-caption"><T>{caption}</T></span></div>)}</section>{d.budgetWarnings?.length > 0 && <section className="mb-4" aria-labelledby="budgetWarningTitle"><div className="section-heading"><h2 id="budgetWarningTitle"><T>{"Yearly budget alerts"}</T></h2><span><T>{"Project costs against allocated budget"}</T></span></div>{d.budgetWarnings.map(w => <div className={`alert ${w.level === 'danger' ? 'alert-danger' : w.level === 'unset' ? 'alert-info' : 'alert-warning'}`} role="status" key={w.year}><strong>{w.year} · {w.level === 'danger' ? tr('Budget reached or exceeded') : w.level === 'unset' ? tr('No positive budget set') : tr('Approaching budget limit')}</strong><p className="mb-0">{w.percentage != null ? tr('{percent}% used · {amount} {status}', {
              percent: w.percentage,
              amount: money(Math.abs(w.remaining), 'EUR'),
              status: tr(w.remaining < 0 ? 'over budget' : 'remaining')
            }) : tr('{amount} in project costs. Set a positive yearly budget to measure usage.', {
              amount: money(Math.abs(w.remaining), 'EUR')
            })}</p></div>)}</section>}<div className="dashboard-lower"><section className="finance-panel"><div className="section-heading"><h2><T>{"Financial overview"}</T></h2><span><T>{"All years · EUR budget; donations by currency"}</T></span></div><div className="balance-block"><span><T>{"Remaining budget"}</T></span><strong>{money(d.remainingBudget)}</strong><p><T>{"Allocated budgets + donations + memberships − project costs"}</T></p></div><div className="finance-line"><span><i className="bi bi-arrow-down-left" /><T>{"Total donations"}</T></span><strong><Totals values={d.donationTotals} /></strong></div>{[['Membership income', d.membershipIncome], ['Project income', d.projectIncome], ['Project costs', d.totalProjectCost]].map(([label, value]) => <div className="finance-line" key={label}><span><i className="bi bi-arrow-up-right" /><T>{label}</T></span><strong>{money(value)}</strong></div>)}</section><section className="quick-panel"><div className="section-heading"><h2><T>{"Pick up from here"}</T></h2><span>{year?.yearValue}</span></div>{yearId ? <div>{[['projects', 'lavender', 'bi-kanban', 'Manage projects', 'Follow progress and coordinate people', ['HEAD', 'SUBHEAD', 'PROJECT_MANAGER', 'VOLUNTEER', 'MEMBER']], ['donations', 'peach', 'bi-heart', 'View donations', 'Keep every contribution organized', ['HEAD', 'SUBHEAD', 'TREASURER', 'MEMBER']], ['events', 'mint', 'bi-calendar-event', 'Explore events', 'Bring your community together', ['HEAD', 'SUBHEAD', 'EVENT_MANAGER', 'VOLUNTEER', 'MEMBER']]].map(([path, color, icon, title, caption, roles]) => <Role roles={roles} key={path}><Link className="quick-link" to={`/years/${yearId}/${path}`}><span className={`metric-icon ${color}`}><i className={`bi ${icon}`} /></span><span><strong><T>{title}</T></strong><small><T>{caption}</T></small></span><i className="bi bi-arrow-up-right" /></Link></Role>)}</div> : <div className="empty-state"><p><T>{"Your workspace is ready for its first year."}</T></p><Role roles={['HEAD']}><Link className="btn btn-primary" to="/years/new"><T>{"Create first year"}</T></Link></Role><Role roles={['SUBHEAD', 'TREASURER', 'MEMBER', 'VOLUNTEER', 'PROJECT_MANAGER', 'EVENT_MANAGER']}><p className="mb-0"><T>{"Ask your organization head to add a yearly record."}</T></p></Role></div>}<Role roles={['HEAD', 'SUBHEAD', 'MEMBER']}><Link className="quick-link" to="/members"><span className="metric-icon sand"><i className="bi bi-people" /></span><span><strong><T>{"Find a member"}</T></strong><small><T>{"Search your community directory"}</T></small></span><i className="bi bi-arrow-up-right" /></Link></Role></section></div></div>}</ResourceState>;
}
